# -*- coding: utf-8 -*-
"""iris1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13eUm3xebJhEb8llJE6XdgMq0O2NXvKS8
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('/content/Iris.csv')
df

plt.figure(figsize=(12,8))
sns.scatterplot(data=df, x='SepalLengthCm',y='SepalWidthCm',hue='Species',s=100)
plt.grid()
plt.show()

plt.figure(figsize=(12,8))
sns.scatterplot(data=df, x='PetalLengthCm',y='PetalWidthCm',hue='Species',s=100)
plt.grid()
plt.show()

df.drop(['Id'],axis=1,inplace=True)
df.info()

plt.figure(figsize=(12,8))
sns.boxplot(data=df, x='Species',y='SepalLengthCm')
plt.grid()
plt.show()

plt.figure(figsize=(12,8))
sns.boxplot(data=df, x='Species',y='PetalLengthCm')
plt.grid()
plt.show()

df.describe()

